### ISSUE TITLE
panic() while attempting to convert WP site

### ISSUE THREAD

**Issue by otoolep** [ashishb/wp2hugo#38]
Downloaded the latest release, then attempted to convert my WP site at philipotoole.com. The tool panic'ed.

```
$ curl -L https://github.com/ashishb/wp2hugo/releases/download/1.6.0/wp2hugo_Linux_x86_64.tar.gz -o wp2hugo_Linux_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5228k  100 5228k    0     0  6086k      0 --:--:-- --:--:-- --:--:-- 11.5M
~/wp2hugo $ ls
wp2hugo_Linux_x86_64.tar.gz
~/wp2hugo $ ls
wp2hugo_Linux_x86_64.tar.gz
~/wp2hugo $ tar xvfz wp2hugo_Linux_x86_64.tar.gz 
LICENSE
README.md
wp2hugo
~/wp2hugo $ ls
LICENSE  README.md  wp2hugo  wp2hugo_Linux_x86_64.tar.gz
~/wp2hugo $ ./wp2hugo -h
Usage of ./wp2hugo:
  -authors string
    	CSV list of author name(s), if provided, only posts by these authors will be processed
  -color-log-output
    	enable colored log output, set false to structured JSON log (default true)
  -continue-on-media-download-error
    	continue processing even if one or more media downloads fail
  -download-media
    	download media files embedded in the WordPress content
  -font string
    	custom font for the output website (default "Lexend")
  -media-cache-dir string
    	dir path to cache the downloaded media files (default "/tmp/wp2hugo-cache")
  -output string
    	dir path to write the Hugo-generated data to (default "/tmp")
  -source string
    	file path to the source WordPress XML file
~/wp2hugo $ ./wp2hugo -source vallified.WordPress.2024-09-03.xml
02:02:24PM DBG main.go:49 > Reading website export source=vallified.WordPress.2024-09-03.xml
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ashishb/wp2hugo/src/wp2hugo/internal/wpparser.getCommonFields(0xc000f7fa00)
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/internal/wpparser/wp_parser_setup.go:284 +0x10a5
github.com/ashishb/wp2hugo/src/wp2hugo/internal/wpparser.getAttachmentInfo(0x820360?)
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/internal/wpparser/wp_parser_setup.go:272 +0x25
github.com/ashishb/wp2hugo/src/wp2hugo/internal/wpparser.(*Parser).getWebsiteInfo(0x0?, 0xc0011b04e0, {0xc001190dc0, 0x0, 0x1})
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/internal/wpparser/wp_parser_setup.go:202 +0x62b
github.com/ashishb/wp2hugo/src/wp2hugo/internal/wpparser.(*Parser).Parse(0xc001d05d07, {0xa89cc0?, 0xc000a94108?}, {0xc000a986a0, 0x1, 0x0?})
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/internal/wpparser/wp_parser_setup.go:177 +0x26e
main.getWebsiteInfo({0x7fffa0956232?, 0x9a1181?})
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/cmd/wp2hugo/main.go:63 +0x7e
main.handle({0x7fffa0956232, 0x4d})
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/cmd/wp2hugo/main.go:50 +0x91
main.main()
	/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo/cmd/wp2hugo/main.go:40 +0xd2
~/wp2hugo $ ls
LICENSE  README.md  wp2hugo  wp2hugo_Linux_x86_64.tar.gz
~/wp2hugo $ 
```

**Comment by ashishb** [comment]
Fixed in https://github.com/ashishb/wp2hugo/commit/5548cad40dccb9dd2d2d8d49d7cb028653235ba5
